import { describe, it } from 'node:test';
import assert from 'node:assert';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  verify, verifyAny, verifyBilateral, verifyBilateralWithOptions, verifyBilateralWithOptionsDetailed, verifyAuthorized,
  type SignetReceipt, type BilateralReceipt, type AuthorizedReceipt,
} from '../src/index.js';

// Long time window so committed fixtures don't expire as wall-clock advances.
// 100 years is effectively "no time-window check" while keeping the API real.
const NO_TIME_WINDOW = 100 * 365 * 24 * 3600;

// Cross-language interop: Python (signet-auth) signs, TypeScript verifies.
//
// Fixtures are generated by:
//   bindings/signet-py/scripts/generate-interop-fixtures.py
// committed at: tests/fixtures/python-signed.json
//
// Both bindings call into the same Rust signet-core, so byte-for-byte
// identity of canonical payloads and signatures is expected.

const __dirname = dirname(fileURLToPath(import.meta.url));
// Path resolves from compiled dist/tests/, walk up to source tests/fixtures.
const FIXTURES_PATH = join(__dirname, '..', '..', 'tests', 'fixtures', 'python-signed.json');

interface Fixtures {
  v1: { receipt: SignetReceipt; public_key: string };
  v2: { receipt: Record<string, unknown>; public_key: string };
  v3: {
    receipt: BilateralReceipt;
    agent_public_key: string;
    server_public_key: string;
  };
  v4: {
    receipt: AuthorizedReceipt;
    delegate_public_key: string;
    owner_public_key: string;
  };
}

const fixtures: Fixtures = JSON.parse(readFileSync(FIXTURES_PATH, 'utf-8'));

describe('cross-language interop: Python sign → TypeScript verify', () => {
  it('verifies a Python-signed v1 unilateral receipt', () => {
    const { receipt, public_key } = fixtures.v1;
    assert.strictEqual(verify(receipt, public_key), true);
  });

  it('rejects a Python-signed v1 receipt with wrong key', () => {
    const { receipt } = fixtures.v1;
    // Use a different fixture's key.
    assert.strictEqual(verify(receipt, fixtures.v2.public_key), false);
  });

  it('detects tampering on a Python-signed v1 receipt', () => {
    const { receipt, public_key } = fixtures.v1;
    const tampered: SignetReceipt = {
      ...receipt,
      action: { ...receipt.action, tool: 'evil_tool' },
    };
    assert.strictEqual(verify(tampered, public_key), false);
  });

  it('verifies a Python-signed v2 compound receipt via verifyAny', () => {
    const { receipt, public_key } = fixtures.v2;
    assert.strictEqual(verifyAny(JSON.stringify(receipt), public_key), true);
  });

  it('verifies a Python-signed v3 bilateral receipt with server key', () => {
    // Use verifyBilateralWithOptions with a long time window so the
    // committed fixture remains valid as wall-clock advances. The default
    // verifyBilateral enforces a 5-minute window which would expire shortly
    // after fixture generation.
    const { receipt, server_public_key } = fixtures.v3;
    assert.strictEqual(
      verifyBilateralWithOptions(receipt, server_public_key, {
        maxTimeWindowSecs: NO_TIME_WINDOW,
        disableReplayCheck: true,
      }),
      true,
    );
  });

  it('verifies a Python-signed v3 bilateral receipt against a trusted agent key', () => {
    const { receipt, server_public_key, agent_public_key } = fixtures.v3;
    assert.strictEqual(
      verifyBilateralWithOptions(receipt, server_public_key, {
        maxTimeWindowSecs: NO_TIME_WINDOW,
        trustedAgentPublicKey: agent_public_key,
        disableReplayCheck: true,
      }),
      true,
    );
    assert.strictEqual(
      verifyBilateralWithOptionsDetailed(receipt, server_public_key, {
        maxTimeWindowSecs: NO_TIME_WINDOW,
        trustedAgentPublicKey: agent_public_key,
        disableReplayCheck: true,
      }),
      'agent_trusted',
    );
  });

  it('verifyAny dispatches Python-signed v3 to bilateral verification', () => {
    // Note: verifyAny uses default options (5-minute window). For long-lived
    // committed fixtures, prefer verifyBilateralWithOptions. We verify dispatch
    // works structurally — actual time-window pass requires fresh receipt.
    const { receipt, server_public_key } = fixtures.v3;
    // Either succeeds (within window) or throws (window exceeded). Both
    // paths exercise the dispatch logic; we tolerate either to keep the
    // committed fixture stable across time.
    try {
      const ok = verifyAny(JSON.stringify(receipt), server_public_key);
      assert.strictEqual(ok, true);
    } catch (err) {
      assert(
        String(err).includes('time') || String(err).includes('window'),
        `unexpected error from verifyAny v3 dispatch: ${err}`,
      );
    }
  });

  it('rejects v3 receipt with wrong server key', () => {
    const { receipt, agent_public_key } = fixtures.v3;
    // Agent key is not the server key. verifyBilateralWithOptions returns
    // false on key mismatch (the WASM wrapper normalizes mismatch errors
    // to a boolean false, distinct from verifyBilateral which throws).
    assert.strictEqual(
      verifyBilateralWithOptions(receipt, agent_public_key, {
        maxTimeWindowSecs: NO_TIME_WINDOW,
        disableReplayCheck: true,
      }),
      false,
    );
  });

  it('verifies a Python-signed v4 authorized receipt against trusted root', () => {
    const { receipt, owner_public_key } = fixtures.v4;
    // verifyAuthorized returns the effective Scope on success or throws.
    const scope = verifyAuthorized(receipt, [owner_public_key]);
    assert(Array.isArray(scope.tools));
    assert(Array.isArray(scope.targets));
  });

  it('rejects v4 receipt against unknown trusted root', () => {
    const { receipt } = fixtures.v4;
    // v1 fixture's key is not the v4 owner; verification must throw.
    assert.throws(
      () => verifyAuthorized(receipt, [fixtures.v1.public_key]),
    );
  });
});
