//! Policy-hash stability vectors (spec §5.3).
//!
//! The expected hashes for the obligation-free fixtures were generated with
//! the released v0.10 code (commit 6272fbf, via a temporary worktree). Adding
//! `Rule.obligations` must not change the hash of a policy that does not use
//! them — attestations already in the field reference those hashes.

use signet_core::{compute_policy_hash, parse_policy_yaml, validate_policy};

const FIXTURE_DIR: &str = "tests/fixtures/policy-hash-vectors";

fn load(name: &str) -> signet_core::Policy {
    let yaml = std::fs::read_to_string(format!("{FIXTURE_DIR}/{name}.yaml"))
        .expect("fixture file must exist");
    let policy = parse_policy_yaml(&yaml).expect("fixture must parse");
    validate_policy(&policy).expect("fixture must validate");
    policy
}

fn hash_of(name: &str) -> String {
    compute_policy_hash(&load(name)).expect("hash must compute")
}

/// Generated by v0.10 (6272fbf).
const MINIMAL_V010: &str =
    "sha256:fc13825e5e76920d8b7257ac0a6939bad6efe9d8da9bb183c82d75273bf296e4";

/// Generated by v0.10 (6272fbf). Exercises every serialization-relevant
/// field that existed in 0.10: matchers, params operators, rate limits.
const FULL_V010: &str = "sha256:6a41f47af95b7c7294520c33498f8871909c16644b74f3ec094b5dd7d5416f28";

#[test]
fn test_policy_hash_matches_v010_vectors() {
    assert_eq!(hash_of("minimal"), MINIMAL_V010);
    assert_eq!(hash_of("full"), FULL_V010);
}

#[test]
fn test_obligation_policy_hash_is_deterministic_and_distinct() {
    // 0.10 could not express obligations, so there is no 0.10 vector for
    // this fixture — pin determinism instead, plus distinctness from the
    // same policy with obligations stripped.
    let h1 = hash_of("with_obligations");
    let h2 = hash_of("with_obligations");
    assert_eq!(h1, h2, "hash must be deterministic");

    let policy = load("with_obligations");
    let without = signet_core::Policy {
        name: policy.name.clone(),
        ..policy.clone()
    };
    // Strip obligations from every rule.
    let stripped: Vec<signet_core::policy::Rule> = without
        .rules
        .iter()
        .map(|r| signet_core::policy::Rule {
            obligations: None,
            ..r.clone()
        })
        .collect();
    let stripped_policy = signet_core::Policy {
        rules: stripped,
        ..without
    };
    let h_stripped = compute_policy_hash(&stripped_policy).unwrap();
    assert_ne!(
        h1, h_stripped,
        "obligations must participate in the policy hash when present"
    );
}

#[test]
fn test_obligation_fixture_carries_obligations_in_eval() {
    let policy = load("with_obligations");
    let action = signet_core::Action {
        tool: "payment".into(),
        params: serde_json::json!({}),
        params_hash: String::new(),
        target: String::new(),
        transport: "stdio".into(),
        session: None,
        call_id: None,
        response_hash: None,
        trace_id: None,
        parent_receipt_id: None,
    };
    let eval = signet_core::evaluate_policy(&action, "agent", &policy, None).unwrap();
    assert_eq!(eval.obligations.len(), 2);
    assert_eq!(eval.obligations[0].ob_type, "require_approval");
    assert_eq!(eval.obligations[1].ob_type, "sandbox");
}
