"""signet-auth: Cryptographic action receipts for AI agents."""

from signet_auth._signet import (
    __version__,
    # Exceptions
    SignetError,
    InvalidKeyError,
    SignatureMismatchError,
    InvalidReceiptError,
    CanonicalizeError,
    SerializeError,
    KeyNotFoundError,
    KeyExistsError,
    InvalidNameError,
    DecryptionError,
    CorruptedFileError,
    CorruptedRecordError,
    SignetIOError,
    UnsupportedFormatError,
    # Types
    Action,
    Signer,
    Receipt,
    KeyPair,
    KeyInfo,
    AuditRecord,
    ChainBreak,
    ChainStatus,
    VerifyFailure,
    VerifyResult,
    # Core functions
    generate_keypair,
    sign,
    verify,
    # Identity functions
    validate_key_name,
    default_signet_dir,
    generate_and_save,
    load_signing_key,
    load_verifying_key,
    load_key_info,
    list_keys,
    export_public_key,
)

__all__ = [
    "__version__",
    # Exceptions
    "SignetError",
    "InvalidKeyError",
    "SignatureMismatchError",
    "InvalidReceiptError",
    "CanonicalizeError",
    "SerializeError",
    "KeyNotFoundError",
    "KeyExistsError",
    "InvalidNameError",
    "DecryptionError",
    "CorruptedFileError",
    "CorruptedRecordError",
    "SignetIOError",
    "UnsupportedFormatError",
    # Types
    "Action",
    "Signer",
    "Receipt",
    "KeyPair",
    "KeyInfo",
    "AuditRecord",
    "ChainBreak",
    "ChainStatus",
    "VerifyFailure",
    "VerifyResult",
    # Core functions
    "generate_keypair",
    "sign",
    "verify",
    # Identity functions
    "validate_key_name",
    "default_signet_dir",
    "generate_and_save",
    "load_signing_key",
    "load_verifying_key",
    "load_key_info",
    "list_keys",
    "export_public_key",
]
