"""signet-auth: Cryptographic action receipts for AI agents."""

from signet_auth.agent import SigningAgent
from signet_auth.decorator import signet_sign, sign, init as init_signer
from signet_auth.server import VerifyOptions, ServerVerifyResult, verify_request
from signet_auth._signet import (
    __version__,
    # Exceptions
    SignetError,
    InvalidKeyError,
    SignatureMismatchError,
    InvalidReceiptError,
    CanonicalizeError,
    SerializeError,
    KeyNotFoundError,
    KeyExistsError,
    InvalidNameError,
    DecryptionError,
    CorruptedFileError,
    CorruptedRecordError,
    SignetIOError,
    UnsupportedFormatError,
    ScopeViolationError,
    ChainError,
    DelegationExpiredError,
    UnauthorizedError,
    PolicyViolationError,
    PolicyParseError,
    RequiresApprovalError,
    # Types
    Action,
    Signer,
    Receipt,
    Response,
    CompoundReceipt,
    ServerInfo,
    BilateralReceipt,
    KeyPair,
    KeyInfo,
    AuditRecord,
    ChainBreak,
    ChainStatus,
    VerifyFailure,
    VerifyResult,
    # Core functions
    generate_keypair,
    sign,
    sign_compound,
    verify,
    verify_any,
    sign_bilateral,
    verify_bilateral,
    verify_bilateral_with_options,
    # Delegation functions
    sign_delegation,
    verify_delegation,
    sign_authorized,
    verify_authorized,
    # Expiration functions
    sign_with_expiration,
    verify_allow_expired,
    # Policy functions
    parse_policy_yaml,
    parse_policy_json,
    evaluate_policy,
    sign_with_policy,
    compute_policy_hash,
    # Identity functions
    validate_key_name,
    default_signet_dir,
    generate_and_save,
    load_signing_key,
    load_verifying_key,
    load_key_info,
    list_keys,
    export_public_key,
    # Audit functions
    audit_append,
    audit_query,
    audit_verify_chain,
    audit_verify_signatures,
)

__all__ = [
    "__version__",
    # High-level class
    "SigningAgent",
    # Exceptions
    "SignetError",
    "InvalidKeyError",
    "SignatureMismatchError",
    "InvalidReceiptError",
    "CanonicalizeError",
    "SerializeError",
    "KeyNotFoundError",
    "KeyExistsError",
    "InvalidNameError",
    "DecryptionError",
    "CorruptedFileError",
    "CorruptedRecordError",
    "SignetIOError",
    "UnsupportedFormatError",
    "PolicyViolationError",
    "PolicyParseError",
    "RequiresApprovalError",
    # Types
    "Action",
    "Signer",
    "Receipt",
    "Response",
    "CompoundReceipt",
    "ServerInfo",
    "BilateralReceipt",
    "KeyPair",
    "KeyInfo",
    "AuditRecord",
    "ChainBreak",
    "ChainStatus",
    "VerifyFailure",
    "VerifyResult",
    # Core functions
    "generate_keypair",
    "sign",
    "sign_compound",
    "verify",
    "verify_any",
    "sign_bilateral",
    "verify_bilateral",
    "verify_bilateral_with_options",
    # Delegation functions
    "sign_delegation",
    "verify_delegation",
    "sign_authorized",
    "verify_authorized",
    # Expiration functions
    "sign_with_expiration",
    "verify_allow_expired",
    # Policy functions
    "parse_policy_yaml",
    "parse_policy_json",
    "evaluate_policy",
    "sign_with_policy",
    "compute_policy_hash",
    # Identity functions
    "validate_key_name",
    "default_signet_dir",
    "generate_and_save",
    "load_signing_key",
    "load_verifying_key",
    "load_key_info",
    "list_keys",
    "export_public_key",
    # Audit functions
    "audit_append",
    "audit_query",
    "audit_verify_chain",
    "audit_verify_signatures",
    # Server verification
    "VerifyOptions",
    "ServerVerifyResult",
    "verify_request",
]
