"""Type stubs for signet_auth._signet (PyO3 extension module)."""

from __future__ import annotations

from datetime import datetime
from typing import Any

__version__: str

# ─── Exceptions ───────────────────────────────────────────────────────────────

class SignetError(Exception): ...
class InvalidKeyError(SignetError): ...
class SignatureMismatchError(SignetError): ...
class InvalidReceiptError(SignetError): ...
class CanonicalizeError(SignetError): ...
class SerializeError(SignetError): ...
class KeyNotFoundError(SignetError): ...
class KeyExistsError(SignetError): ...
class InvalidNameError(SignetError): ...
class DecryptionError(SignetError): ...
class CorruptedFileError(SignetError): ...
class CorruptedRecordError(SignetError): ...
class SignetIOError(SignetError): ...
class UnsupportedFormatError(SignetError): ...

# ─── Types ────────────────────────────────────────────────────────────────────

class Action:
    def __init__(
        self,
        tool: str,
        params: Any | None = None,
        target: str = "",
        transport: str = "stdio",
        session: str | None = None,
        call_id: str | None = None,
        response_hash: str | None = None,
    ) -> None: ...
    @classmethod
    def hash_only(
        cls,
        tool: str,
        params_hash: str,
        *,
        target: str = "",
        transport: str = "stdio",
        session: str | None = None,
        call_id: str | None = None,
        response_hash: str | None = None,
    ) -> Action: ...
    @property
    def tool(self) -> str: ...
    @property
    def params(self) -> Any | None: ...
    @property
    def params_hash(self) -> str: ...
    @property
    def target(self) -> str: ...
    @property
    def transport(self) -> str: ...
    @property
    def session(self) -> str | None: ...
    @property
    def call_id(self) -> str | None: ...
    @property
    def response_hash(self) -> str | None: ...

class Signer:
    @property
    def pubkey(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def owner(self) -> str: ...

class Receipt:
    @property
    def v(self) -> int: ...
    @property
    def id(self) -> str: ...
    @property
    def action(self) -> Action: ...
    @property
    def signer(self) -> Signer: ...
    @property
    def ts(self) -> str: ...
    @property
    def nonce(self) -> str: ...
    @property
    def sig(self) -> str: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json_str: str) -> Receipt: ...

class KeyPair:
    secret_key: str
    public_key: str
    def __repr__(self) -> str: ...

class KeyInfo:
    name: str
    owner: str | None
    pubkey: str
    created_at: str

class AuditRecord:
    @property
    def receipt(self) -> Receipt: ...
    @property
    def prev_hash(self) -> str: ...
    @property
    def record_hash(self) -> str: ...

class ChainBreak:
    file: str
    line: int
    expected_hash: str
    actual_hash: str

class ChainStatus:
    total_records: int
    valid: bool
    @property
    def break_point(self) -> ChainBreak | None: ...

class VerifyFailure:
    file: str | None
    line: int | None
    receipt_id: str
    reason: str

class VerifyResult:
    total: int
    valid: int
    @property
    def failures(self) -> list[VerifyFailure]: ...

# ─── Core functions ───────────────────────────────────────────────────────────

def generate_keypair() -> KeyPair: ...
def sign(
    secret_key: str,
    action: Action,
    signer_name: str,
    signer_owner: str | None = None,
) -> Receipt: ...
def verify(receipt: Receipt, public_key: str) -> bool: ...

# ─── Identity functions ───────────────────────────────────────────────────────

def validate_key_name(name: str) -> None: ...
def default_signet_dir() -> str: ...
def generate_and_save(
    dir: str,
    name: str,
    owner: str | None = None,
    passphrase: str | None = None,
) -> KeyInfo: ...
def load_signing_key(
    dir: str,
    name: str,
    passphrase: str | None = None,
) -> str: ...
def load_verifying_key(dir: str, name: str) -> str: ...
def load_key_info(dir: str, name: str) -> KeyInfo: ...
def list_keys(dir: str) -> list[KeyInfo]: ...
def export_public_key(dir: str, name: str) -> dict[str, Any]: ...

# ─── Audit functions ──────────────────────────────────────────────────────────

def audit_append(dir: str, receipt: Receipt) -> AuditRecord: ...
def audit_query(
    dir: str,
    *,
    since: str | datetime | None = None,
    tool: str | None = None,
    signer: str | None = None,
    limit: int | None = None,
) -> list[AuditRecord]: ...
def audit_verify_chain(dir: str) -> ChainStatus: ...
def audit_verify_signatures(
    dir: str,
    *,
    since: str | datetime | None = None,
    tool: str | None = None,
    signer: str | None = None,
    limit: int | None = None,
) -> VerifyResult: ...
